// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using hyperdevCase.DataAccess;

#nullable disable

namespace hyperdevCase.DataAccess.Migrations
{
    [DbContext(typeof(hyperDevCaseDBContext))]
    [Migration("20220708120007_create-db-postgresql")]
    partial class createdbpostgresql
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("hyperdevCase.Entities.Concrete.AltDepartman", b =>
                {
                    b.Property<int>("altDepartmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("altDepartmanID"));

                    b.Property<string>("altDepartmanAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("ustDepartmanIDdepartmanID")
                        .HasColumnType("integer");

                    b.HasKey("altDepartmanID");

                    b.HasIndex("ustDepartmanIDdepartmanID");

                    b.ToTable("AltDepartmanlar");
                });

            modelBuilder.Entity("hyperdevCase.Entities.Concrete.Departman", b =>
                {
                    b.Property<int>("departmanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("departmanID"));

                    b.Property<string>("departmanAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("departmanSirketIDsirketID")
                        .HasColumnType("integer");

                    b.HasKey("departmanID");

                    b.HasIndex("departmanSirketIDsirketID");

                    b.ToTable("Departmanlar");
                });

            modelBuilder.Entity("hyperdevCase.Entities.Concrete.Sirket", b =>
                {
                    b.Property<int>("sirketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sirketID"));

                    b.Property<string>("sirketAdi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("sirketAdres")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("sirketIl")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("sirketIlce")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("sirketTur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("sirketVD")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("sirketVNO")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("sirketID");

                    b.ToTable("Sirketler");
                });

            modelBuilder.Entity("hyperdevCase.Entities.Concrete.AltDepartman", b =>
                {
                    b.HasOne("hyperdevCase.Entities.Concrete.Departman", "ustDepartmanID")
                        .WithMany()
                        .HasForeignKey("ustDepartmanIDdepartmanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ustDepartmanID");
                });

            modelBuilder.Entity("hyperdevCase.Entities.Concrete.Departman", b =>
                {
                    b.HasOne("hyperdevCase.Entities.Concrete.Sirket", "departmanSirketID")
                        .WithMany()
                        .HasForeignKey("departmanSirketIDsirketID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("departmanSirketID");
                });
#pragma warning restore 612, 618
        }
    }
}
